Update some basic info on processing tx fee
amolabs/docs pull request #5
Opened 2019-10-08 06:28 UTC by h0n9

resolves https://github.com/amolabs/docs/issues/4

2019-10-08 06:31 UTC, h0n9 commented
It is required to consider **WHEN** to transfer `fee` to a validator account.
while processing `DeliverTx` or `Commit`

2019-10-10 04:49 UTC, Lbird requested changes

2019-10-10 04:49 UTC, Lbird commented on protocol.md
> +	"fee": "_currency_",
Tab? or space?

2019-10-10 04:49 UTC, Lbird commented on protocol.md
> +`_sender_address_` identifies the sender or originator of this transaction. `"nonce"` is a ***random*** byte sequence with the length of 20 bytes represented by HEX-encoding(See [Replay Attack](#repl
block validator -> block proposer

2019-10-10 04:49 UTC, Lbird commented on protocol.md
> +1. `validator_balance` &larr; `validator_balance` + `fee`
validator -> block proposer

2019-10-10 04:49 UTC, Lbird commented on protocol.md
> +1. `validator_balance` &larr; `validator_balance` + `fee`
validator -> block proposer

2019-10-10 04:49 UTC, Lbird commented on protocol.md
> +1. `validator_balance` &larr; `validator_balance` + `fee`
validator -> block proposer

2019-10-10 04:49 UTC, Lbird commented on protocol.md
> +1. `validator_balance` &larr; `validator_balance` + `fee`
validator -> block proposer

2019-10-10 04:49 UTC, Lbird commented on protocol.md
> +1. `validator_balance` &larr; `validator_balance` + `fee`
validator -> block proposer

2019-10-10 05:46 UTC, Lbird approved these changes

2019-10-10 05:46 UTC, merged